# Generated by Django 4.2 on 2025-05-08 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cca2', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('cca3', models.CharField(max_length=3, unique=True)),
                ('ccn3', models.CharField(blank=True, max_length=3, null=True)),
                ('common_name', models.CharField(max_length=100)),
                ('official_name', models.CharField(max_length=200)),
                ('independent', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50)),
                ('un_member', models.BooleanField(default=False)),
                ('cioc', models.CharField(blank=True, max_length=3, null=True)),
                ('fifa', models.CharField(blank=True, max_length=3, null=True)),
                ('region', models.CharField(max_length=50)),
                ('subregion', models.CharField(blank=True, max_length=50, null=True)),
                ('continent', models.CharField(max_length=20)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('landlocked', models.BooleanField(default=False)),
                ('area', models.FloatField(blank=True, null=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('capital_lat', models.FloatField(blank=True, null=True)),
                ('capital_lng', models.FloatField(blank=True, null=True)),
                ('timezone', models.CharField(max_length=20)),
                ('start_of_week', models.CharField(default='monday', max_length=10)),
                ('population', models.PositiveIntegerField()),
                ('gini', models.JSONField(blank=True, null=True)),
                ('flag_emoji', models.CharField(max_length=10)),
                ('flag_png', models.URLField()),
                ('flag_svg', models.URLField()),
                ('flag_alt', models.TextField(blank=True, null=True)),
                ('coat_of_arms_png', models.URLField(blank=True, null=True)),
                ('coat_of_arms_svg', models.URLField(blank=True, null=True)),
                ('car_signs', models.CharField(blank=True, max_length=100, null=True)),
                ('car_side', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', max_length=10)),
                ('tld', models.CharField(blank=True, max_length=200, null=True)),
                ('postal_code_format', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code_regex', models.CharField(blank=True, max_length=200, null=True)),
                ('google_maps', models.URLField(blank=True, null=True)),
                ('openstreet_maps', models.URLField(blank=True, null=True)),
                ('borders', models.CharField(blank=True, max_length=500, null=True)),
                ('alt_spellings', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['common_name'],
            },
        ),
        migrations.CreateModel(
            name='IDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(max_length=5)),
                ('suffixes', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idd', to='countries.country')),
            ],
            options={
                'verbose_name': 'International Direct Dialing',
                'verbose_name_plural': 'IDD information',
            },
        ),
        migrations.CreateModel(
            name='CapitalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capital_info', to='countries.country')),
            ],
            options={
                'verbose_name_plural': 'capital info',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('official', models.TextField()),
                ('common', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='countries.country')),
            ],
            options={
                'unique_together': {('country', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='NativeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('official', models.TextField()),
                ('common', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='native_names', to='countries.country')),
            ],
            options={
                'verbose_name_plural': 'native names',
                'unique_together': {('country', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='countries.country')),
            ],
            options={
                'unique_together': {('country', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Demonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('masculine', models.CharField(blank=True, max_length=50, null=True)),
                ('feminine', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demonyms', to='countries.country')),
            ],
            options={
                'unique_together': {('country', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='countries.country')),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'unique_together': {('country', 'code')},
            },
        ),
    ]
